[package]
name = "xtask"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
clap = { features = [ "derive", "env" ], workspace = true }
octocrab = { default-features = false, features = [
  "default-client",
  "jwt-rust-crypto",
  "rustls",
  "rustls-ring",
], workspace = true }
regex = { workspace = true }
reqwest = { default-features = false, features = [ "rustls" ], workspace = true }
serde = { features = [ "derive" ], workspace = true }
tokio = { features = [ "macros", "rt-multi-thread" ], workspace = true }
toml = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
