name: ci

on:
  pull_request:
  push:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: true
  RUSTC_WRAPPER: sccache

jobs:
  test:
    name: test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            command: cargo test --workspace --all-features
          - os: macos-latest
            command: cargo test --workspace --all-features
          - os: windows-latest
            command: cargo test --workspace --all-features

    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@stable

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.10

      - name: Setup mold
        if: runner.os == 'Linux'
        uses: rui314/setup-mold@v1

      - name: Run tests
        run: ${{ matrix.command }}

  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.10

      - name: Setup mold
        uses: rui314/setup-mold@v1

      - name: Lint code
        run: cargo clippy --workspace --all-features --all-targets -- -D warnings

  machete:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.10

      - name: Machete
        uses: bnjbvr/cargo-machete@main

  rust-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@stable

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.10

      - name: Setup mold
        uses: rui314/setup-mold@v1

      - uses: cargo-bins/cargo-binstall@main

      - name: Install cargo-llvm-cov
        shell: bash
        run: cargo binstall cargo-llvm-cov --locked --no-confirm

      - name: Run coverage
        shell: bash
        run: |
          cargo llvm-cov clean --workspace
          cargo llvm-cov --workspace --all-features --all-targets --cobertura --output-path=target/cobertura.xml

      - name: Codecov publish
        uses: codecov/codecov-action@v7
        with:
          files: target/cobertura.xml
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Codecov housekeeping
        shell: bash
        run: |
          rm -f codecov codecov.SHA256SUM codecov.SHA256SUM.sig
